### ISSUE TITLE
Wrong number of values to unpack in task.py

### ISSUE THREAD

**Issue by tbrent** [emlynoregan/appenginetaskutils#1]
I've run into a bug with `_run()` in `task.py`. The bug occurs sometimes and not others. I believe it might have something to do with how the function is pickled. The bug seems to occur only when larger functions are pickled, but not with smaller ones. 

The failure occurs on line 43 of `task.py`:
func, args, kwargs, passthroughargs = pickle.loads(data)

The exception is: `PermanentTaskFailure: need more than 3 values to unpack`. I believe it is occurring because sometimes `pickle.loads()` returns 3 values, and sometimes 4. I have been able to workaround this bug by making all my tasks accept optional headers, and using the following lines of code in `task.py`:

    try:
        func, args, kwargs, passthroughargs = pickle.loads(data)
    except Exception, e:
        try:
            func, args, kwargs = pickle.loads(data)
        except Exception, e:
            raise PermanentTaskFailure(e)
    kwargs["headers"] = headers
    func(*args, **kwargs)

I've also noticed that if I don't set `"headers"` then `_run_from_datastore()` fails because it was expecting 2 arguments but only gets 1. 

Hope some of this is making sense.

**Comment by emlynoregan** [comment]
That makes complete sense. 

The bug looks like it is here:

```
    def runtask(*args, **kwargs):
        pickled = yccloudpickle.dumps((f, args, kwargs, passthroughargs))  ## 4 args
        try:
            task = taskqueue.Task(payload=pickled, **taskkwargscopy)
            return task.add(queue, transactional=transactional)
        except taskqueue.TaskTooLargeError:
            key = _TaskToRun(data=pickled, parent=parent).put()
            rfspickled = yccloudpickle.dumps((_run_from_datastore, [key], {}))  ## 3 args
            task = taskqueue.Task(payload=rfspickled, **taskkwargscopy)
            return task.add(queue, transactional=transactional)
```
I suspect if I just add "passthroughargs to the second dumps line, that'll help. There needs to be some extra fiddling to sort out that issue with "headers".

There should be a fix shortly.

**Comment by emlynoregan** [comment]
Here's a fixed version, in the dev branch:

https://github.com/emlynoregan/appenginetaskutils/blob/dev/taskutils/task.py

Do you mind trying it out, letting me know how that goes?

**Comment by tbrent** [comment]
Sure thing.

**Comment by tbrent** [comment]
Seems to be working. The `PermanentTaskFailure` error has stopped popping up. 

Just for completeness, I'll add that I have started seeing `Request was aborted after waiting too long to attempt to service your request.` errors, but I think that's related to going from 0 to 60 too fast for App Engine's horizontal scaling to handle. I don't think it's related to `task.py`. 

I'll continue using task over deferred and post feedback here as it arises. Thanks again

**Comment by tbrent** [comment]
Did not mean to close

**Comment by emlynoregan** [comment]
Thanks for testing that code!

I'll add it to the python package and push the new version.

Just out of interest, are you using the package and pypi, or just including the code directly?

Also, I'm interested that you were hitting that issue at all. It'll only happen if you are serialising between 100kb and 1mb (ie: from code+args+closure combined). I haven't seen it because nothing I'm doing gets this big.

It might be a sign that you're, for instance, accidentally touching some large chunk of data that really doesn't need to move around this way. 

Also a heads-up, if you go bigger than 1mb, you'll hit the limit on size of datastore objects, and get a hard fail. It gets pretty tough to go any bigger, although if you've got a serious use case and/or a clever idea for getting past this limit, let me know :-)

**Comment by tbrent** [comment]
In general I'm using the package by including it in my requirements.txt file and vendoring it in. For the testing of your change to task.py in the develop branch I got lazy and just modified task.py directly. 

In my tasks I serialize a bit of meaningless overhead (2 integers and a string), and then an instance of a KeyRange object. I haven't sized the KeyRange object out yet, but given that you're doing the same, I'm not sure what's pushing me over the 100kb limit. I'm almost certainly going over it though.

Unrelated misc-question.
I've been dealing with non-deterministic `cannot import name XXXXXX` errors for a while now, where XXXXXX is an object not used in my tasks, but one that gets looked for nonetheless. Likewise, when I add @auth decorators to my handlers, and call a task, it also triggers the error. The error doesn't occur when I trigger only a few tasks, and occurs in vast number when I trigger many. I think it's related to certain instances not having the correct namespace or context or something related, which is the issue this guy had: http://stackoverflow.com/questions/27789874/deferred-tasks-creates-new-instances-that-cant-access-some-python-modules

Just including this in case you've faced the same problem. My next step for debugging is separating my tasks out into a different service entirely.

**Comment by emlynoregan** [comment]
I've definitely faced that importing issue. It's a real pain.

What's happening is this: When you enqueue a task, it might get run by either:

- an instance that's already been used for other stuff (eg: the instance that enqueued it), 
or 
- a new instance that's just been spun up, and it's the first thing to run.

If it runs on an older instance, it's going to be fine; all the modules you'll use are loaded, your whole initialisation process has run.

But on a brand new instance, you might be entirely skipping the normal initialisation process for your code. So you can get errors like this:

PermanentTaskFailure: No module named app.Report

because a particular module was never imported, or you can get "cannot import" errors that might indicate that your vendoring code is being skipped, or some other weird effect of not constructing your app as other calls normally do.

If you are importing @task in the way I describe in the @task article, ie: via a handler like this:

```
handlers:
    - url: /_ah/task/.*
      script: taskutils.app
      login: admin

``` 
then this is probably happening to you. You can see it's saying to go load the module taskutils.py (likely from a lib folder via vendoring) and pass the call to the global "app" object in there. 

If you've got a big, complex app, with something like a main.py that you use for most calls, all your imports probably happen there. That's certainly the case for me. But if you use the handler as above, that main.py doesn't gets loaded for the new instance, imports don't happen, stuff breaks.

There are some alternative ways to wire @task into your app. I think you're using flask, so checkout the bottom of task.py:

```
def setuptasksforflask(flaskapp):
    @flaskapp.route(_DEFAULT_FLASK_URL, methods=["POST"])
    def taskhandler(fmodule, ffunction):
        _launch_task(flask.request.data, "%s/%s" % (fmodule, ffunction), flask.request.headers)
        return ""

```

If you've got some central _main.py_ or similar that normally handles your calls, and constructs your flask app, you can just add this:

```
  from taskutils import setuptasksforflask

  # do stuff that creates your flask app, "app".

  setuptasksforflask(app)

```
then change your app.yaml handler to be

```
handlers:
    - url: /_ah/task/.*
      script: main.app        ### <-- this assumes main.py, with flask app called "app"
      login: admin
```

Now @task calls are correctly constructing your whole app if that hasn't happened already, and you should see these import issues go away.

**Comment by tbrent** [comment]
It worked! Wow, thank you so much Emlyn! That problem has been on the back-burner for far too long and this simple three-liner solved everything. Really, I can't thank you enough, this is a huge relief!

**Comment by emlynoregan** [comment]
No worries! I had the same problem that dogged me for months, I remember the relief :-) I should probably write an article about it.

**Comment by tbrent** [comment]
You should! You could also choose to sport this as a feature in your `README.md` to draw more people to the library. Maybe both!
